apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: demo 
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 8080  # Port on the pods
    nodePort: 30000   # Port accessible externally on each node
  selector:
    app: demo