apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: webserver
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80